"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var authController_1 = require("../../controller/auth/authController");
var authRrouter = (0, express_1.Router)();
authRrouter.post('/register', authController_1.register);
authRrouter.post('/login', authController_1.login);
authRrouter.post('/verify', authController_1.verify);
authRrouter.post('/request-reset-password', authController_1.requestResetPassword);
authRrouter.post('/reset-password', authController_1.resetUserPassword);
exports.default = authRrouter;
