"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var body_parser_1 = require("body-parser");
// import csrf from 'csurf';
var express_1 = require("express");
var helmet_1 = require("helmet");
var routes_1 = require("./routes");
var rate_limit_config_1 = require("./config/rate-limit.config");
var cors_config_1 = require("./config/cors.config");
var morgan_config_1 = require("./config/morgan.config");
var app = (0, express_1.default)();
app.use((0, helmet_1.default)());
app.use(express_1.default.json());
app.use(cors_config_1.corsConfig);
app.use(morgan_config_1.morganConfig);
app.use(body_parser_1.default.json());
app.use(rate_limit_config_1.apiLimiter, routes_1.default);
// app.use(csrf({ cookie: true }));
exports.default = app;
